spring.application.name=url-shortener

# application
server.port = 8090
spring.mvc.problemdetails.enabled=true
spring.profiles.active=prod
spring.jackson.deserialization.fail-on-unknown-properties=true
app.base-url=http://localhost:8090